name: repo create

on:
 
 workflow_dispatch:
    inputs:
      repo:
        description: 'Repository name'     
        required: true
      org:
        type: choice
        description: Select Organization
        options:
        - Amogh-Sdm-Org
        - Test-org
        - Unit-II-Org
      
#       Collaborator:
#         description: 'Collaborator GitHub-Handle'      
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#         python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.9"]
    steps:
       - name: create-repo
         uses: Appu-Test-org/repo-js@main
         with:
           repo: ${{ github.event.inputs.repo}}
           owner: ${{ github.event.inputs.owner}}
           token: ${{ secrets.token }}
#     - uses: actions/checkout@v2
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pylint
#         pip install requests
#     - name: printing Env variables
#       uses: actions/checkout@v2
#     - name: Executing python main()
#       env: 
#         github_url: https://api.github.com
#         org_name: ${{ github.event.inputs.org }}
#         owner: ${{ github.repository_owner }}
#         git_user: Amoghgiri
#         token: ${{ secrets.token}}
#         repo: ${{ github.event.inputs.repo }}
#         member: ${{ github.event.inputs.Collaborator}}
#       run: |
#         python main.py
# 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
